"""empty message

Revision ID: 3c5768427323
Revises: 8df63c061dff
Create Date: 2023-09-01 22:19:00.752270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5768427323'
down_revision = '8df63c061dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('come_menber', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('comeuser',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('not_comeuser',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('come_menber', schema=None) as batch_op:
        batch_op.alter_column('not_comeuser',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('comeuser',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
