"""empty message

Revision ID: 745c934c743b
Revises: 586e5428d76d
Create Date: 2023-08-30 23:08:20.096789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745c934c743b'
down_revision = '586e5428d76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enable_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enable_day')
    # ### end Alembic commands ###
