"""empty message

Revision ID: 79fa531f4875
Revises: cc5acc233fcc
Create Date: 2023-09-08 14:22:37.132188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fa531f4875'
down_revision = 'cc5acc233fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('each_snack', schema=None) as batch_op:
        batch_op.drop_constraint('fk_each_snack_id_user_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_each_snack_id_user_user'), 'user', ['id_user'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('each_snack', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_each_snack_id_user_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_each_snack_id_user_user', 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###
