"""empty message

Revision ID: 8df63c061dff
Revises: 745c934c743b
Create Date: 2023-09-01 21:10:25.347981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df63c061dff'
down_revision = '745c934c743b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('come_menber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('comeuser', sa.Text(), nullable=True),
    sa.Column('not_comeuser', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('come_menber')
    # ### end Alembic commands ###
