"""empty message

Revision ID: c1b7634aadb0
Revises: d7b85a98557e
Create Date: 2023-09-05 17:33:16.032645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b7634aadb0'
down_revision = 'd7b85a98557e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('come_menber', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_come_menber_date'), ['date'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_name'), type_='unique')

    with op.batch_alter_table('come_menber', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_come_menber_date'), type_='unique')

    # ### end Alembic commands ###
