"""empty message

Revision ID: c2371dce0667
Revises: 79fa531f4875
Create Date: 2023-09-10 19:26:40.295089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2371dce0667'
down_revision = '79fa531f4875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('each_snack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_user', sa.String(length=150), nullable=False))
        batch_op.drop_constraint('fk_each_snack_id_user_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_each_snack_username_user_user'), 'user', ['username_user'], ['username'])
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('each_snack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_each_snack_username_user_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_each_snack_id_user_user', 'user', ['id_user'], ['username'])
        batch_op.drop_column('username_user')

    # ### end Alembic commands ###
