"""empty message

Revision ID: cc5acc233fcc
Revises: c1b7634aadb0
Create Date: 2023-09-05 17:35:27.687276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5acc233fcc'
down_revision = 'c1b7634aadb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('each_snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=200), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_each_snack_id_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_each_snack'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('each_snack')
    # ### end Alembic commands ###
